export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminInventoryLayout({ children }) {
  return <section>{children}</section>;
}
