import "./globals.css";
import NextUiProvider from "./NextUiProvider";
import NavBar from "@/components/NavBar";
import AuthProvider from "@/components/AuthProvider";
// import { Provider } from "react-redux";
// import store from "@/redux/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <body>
          <NextUiProvider>
            <header>
              <NavBar />
            </header>
            <main>{children}</main>
          </NextUiProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
